### ISSUE TITLE
睡眠正常吗？

### ISSUE THREAD

**Issue by okaytony** [W-MS/OptiPlex-7060and7070-Catalina#1]
我在MT机型上，睡眠关闭硬盘后唤醒后进入到登陆节目后死机， 0x8dc 0x2 in a UEFI Shell to update DVMT settings.这个一定要改吗？

**Comment by W-MS** [comment]
DVMT不修改可能无法启动，但我不确定MT可以用一样的参数。睡眠在我的MFF上测试并不死机。

**Comment by W-MS** [comment]
先关闭issue了，有问题欢迎再回复。
