### ISSUE TITLE
睡眠后无法正常唤醒，屏幕变绿。

### ISSUE THREAD

**Issue by webleon** [W-MS/OptiPlex-7060and7070-Catalina#10]
机器为 7070SFF，
配置如下：
CPU：i7 9700
显卡：集成 UHD 630
内存：16G x 4  
硬盘：NVMe M.2 256G
显示器：27寸4K x 2 （均为DP输出）
系统：Catalina 10.15.2 （黑果小兵的镜像安装后替换EFI）_

已经修改DVMT，并使用了本项目中的EFI文件夹，大部分功能都正常，只是要从睡眠中唤醒的时候，后会变成绿屏无法正常唤醒。

用电源键唤醒和更换不同USB接口，通过USB设备唤醒都是同样的问题；
拔掉一个显示器只用一个显示器的时候，也是故障依旧。

不知是否能提供一个修复的思路？先多谢。

**Comment by W-MS** [comment]
我倒是没遇到过绿屏的问题，但如果是开机进度条60%开始显示输出就出错的话我还是会怀疑DVMT是否正确设置了。一些镜像会用其他方式纠正小容量DVMT问题但我建议能修改bios的情况下不要增加额外的kext
可以先试试 如果DVMT已经是最大了考虑看看系统中的kext文件

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WebLeOn <notifications@github.com&gt;
发送时间: 2020年1月4日 09:35
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 睡眠后无法正常唤醒，屏幕变绿。 (#10)




机器配置为 7070SFF，
 CPU：i7 9700
 显卡：集成 UHD 630
 内存：16G4
 硬盘：NVMe M.2 256G
 显示器：27寸4K2 （均为DP输出）
 系统：Catalina 10.15.2 （黑果小兵的镜像安装后替换EFI）
 使用了项目中的EFI文件夹，大部分功能都正常，只是要从睡眠中唤醒的时候，后会变成绿屏无法正常唤醒。
 
用电源键唤醒和更换不同USB接口，通过USB设备唤醒都是同样的问题；
 拔掉一个显示器只用一个显示器的时候，也是故障依旧。
 
不知是否能提供一个修复的思路？先多谢。

**Comment by webleon** [comment]
目前开机启动过程是正常的，进度条过程中中间有一次白苹果Logo从大变小的过程。

是进入系统后，睡眠的情况下使用电源键或者USB设备唤醒的时候会绿屏（刚刚接了一个1080P的显示器，同样无法唤醒，但屏幕是黑屏）。

是否建议DVMT设置得比0x2更大？

另外，系统中的kext，是指 /Library/Extensions 中么？
目前内容如下：
ACS6x.kext			EnergyDriver.kext
ATTOCelerityFC8.kext		HighPointIOP.kext
ATTOExpressSASHBA2.kext		HighPointRR.kext
ATTOExpressSASRAID2.kext	PromiseSTEX.kext
ArcMSR.kext			SoftRAID.kext
CalDigitHDProDrv.kext
看不出有何异常。

**Comment by SnrtIevg** [comment]
@webleon
你这个问题解决了吗， 我的问题和你说的 1080 的一样， 睡眠后无法唤醒， 需要重启， 搞得我很难受

**Comment by webleon** [comment]
@SnrtIevg BIOS中打开 Block Deep Sleep
