### ISSUE TITLE
每次启动都有报kernel panic

### ISSUE THREAD

**Issue by huahuahuahuahuahuahuahua** [W-MS/OptiPlex-7060and7070-Catalina#11]
机型是7060m，因为第一次装黑苹果，不清楚panic的原因，如果清楚的话麻烦告知一下，错误日志如下。

我会继续尝试能google到的方法，如果解决了会在该issue回复。

```
panic(cpu 8 caller 0xffffff7f99080305): assertmsg@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-10.34.27/Common/IONDRV/Intel/KBL/AppleIntelFramebuffer/AppleIntelController.cpp:27617
Backtrace (CPU 8), Frame : Return Address
0xffffff8207a23a80 : 0xffffff8016c6d166 
0xffffff8207a23ad0 : 0xffffff8016d95824 
0xffffff8207a23b10 : 0xffffff8016d87b10 
0xffffff8207a23b90 : 0xffffff8016c1f180 
0xffffff8207a23bb0 : 0xffffff8016c6cbdc 
0xffffff8207a23ce0 : 0xffffff8016c6c99c 
0xffffff8207a23d40 : 0xffffff7f99080305 
0xffffff8207a23db0 : 0xffffff7f9907cd32 
0xffffff8207a23e40 : 0xffffff801727327d 
0xffffff8207a23e80 : 0xffffff8017272fc1 
0xffffff8207a23f00 : 0xffffff80172724e7 
0xffffff8207a23f50 : 0xffffff8017274146 
0xffffff8207a23fa0 : 0xffffff8016c1e4f7 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelKBLGraphicsFramebuffer(10.3.4)[7EAAC876-407A-3AAF-8292-CE047EF6B232]@0xffffff7f99054000->0xffffff7f99234fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1057F053-73DE-33E4-B5BE-09DA28715DB4]@0xffffff7f97494000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f9751f000
            dependency: com.apple.iokit.IOAcceleratorFamily2(378.18.1)[BAA0383C-9650-3934-B04A-69008F757A2C]@0xffffff7f98fbd000
            dependency: com.apple.iokit.IOReportFamily(31)[D2F2FBDF-4EE4-38BA-99F5-B699F886F413]@0xffffff7f98054000
            dependency: com.apple.AppleGraphicsDeviceControl(3.18.52)[FC5E4CD4-7730-3A55-9CC5-338A64F50E42]@0xffffff7f97fdc000
            dependency: com.apple.iokit.IOGraphicsFamily(519.19)[0B3857C5-9040-3A0C-BFB4-C45E56DB01C6]@0xffffff7f97ccc000

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 -disablegfxfirmware 

Mac OS version:
17F77

Kernel version:
Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
Kernel UUID: CC1699EE-71B5-3AF1-AAA3-6DBD16222B92
Kernel slide:     0x0000000016a00000
Kernel text base: 0xffffff8016c00000
__HIB  text base: 0xffffff8016b00000
System model name: iMac14,2 (Mac-27ADBB7B4CEE8E61)

System uptime in nanoseconds: 10095042857
last loaded kext at 10091647641: >!A!IKBLGraphics	10.3.4 (addr 0xffffff7f99235000, size 1224704)
loaded kexts:
as.lvs1974.!IGraphicsFixup	1.2.7
as.vit9696.Lilu	1.2.3
org.netkas.driver.FakeSMC	1787
>!A!IKBLGraphics	10.3.4
>!ATyMCEDriver	1.0.3d2
>!A!IKBLGraphicsFramebuffer	10.3.4
>!AGraphicsDevicePolicy	3.18.52
@AGDCPluginDisplayMetrics	3.18.52
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	6.0.6f2
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!ISlowAdaptiveClocking	4.0.0
>!AOSXWatchdog	1
>ACPI_SMC_PlatformPlugin	1.0.0
>!A16X50ACPI	3.2
>!AFIVRDriver	4.1.0
>!AFileSystemDriver	3.0.1
@filesystems.hfs.kext	407.50.6
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!ASystemPolicy	1.0
@filesystems.apfs	748.51.0
>!AAHCIPort	329.50.2
>!AACPIButtons	6.1
>!ARTC	2.0
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
@nke.applicationfirewall	183
$TMSafetyNet	8
$quarantine	3
|IONDRVSupport	519.19
|IOAccelerator!F2	378.18.1
>!AGraphicsControl	3.18.52
>!ASSE	1.0
|IOSurface	211.12
>!AHDA!C	281.52
|IOHDA!F	281.52
|IOAudio!F	206.5
@vecLib.kext	1.2.0
>!ASMBusPCI	1.0.14d1
|IO!BHost!CUSBTransport	6.0.6f2
|IO!BHost!CTransport	6.0.6f2
|IO!B!F	6.0.6f2
@!AGPUWrangler	3.18.52
@!AGraphicsDeviceControl	3.18.52
|IOGraphics!F	519.19
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPluginLegacy	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!A16X50Serial	3.2
|IOSerial!F	11
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.1
>!AXsanScheme	3
|IONVMe!F	2.1.0
|IOAHCI!F	288
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	480.60.1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	439.60.2
>!AMobileFileIntegrity	1.0.5
|IOUSBMass!SDriver	140.50.3
|IOSCSIBlockCommandsDevice	404.30.2
|IOSCSIArchitectureModel!F	404.30.2
|IO!S!F	2.1
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOReport!F	31
|IOTimeSync!F	680.15
|IONetworking!F	3.4
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0



```

**Comment by huahuahuahuahuahuahuahua** [comment]
现在发现，每次启动时报错的都是 10095042857，和uptime不对应。怀疑是某次故障残留下来的。重装之后出的panic也是10095042857

**Comment by huahuahuahuahuahuahuahua** [comment]
目前看上去这个panic没有什么影响，功能都是正常的。
尝试过重建缓存，无效。

当前使用的驱动：
```
➜  Install kextstat | grep -y appleintel

  112    0 0xffffff7f842dd000 0x2000     0x2000     com.apple.driver.AppleIntelSlowAdaptiveClocking (4.0.0) 6C8857B3-D2F7-3D81-AD46-9E3DA63311F0 <111 5 3>
  118    0 0xffffff7f846f8000 0x22e000   0x22e000   com.apple.driver.AppleIntelCFLGraphicsFramebuffer (14.0.3) 2E9737E3-9C0A-33C1-83E4-59B437F968FB <117 116 115 17 13 12 8 7 6 5 3 1>
  127    0 0xffffff7f83ee8000 0xf3000    0xf3000    com.apple.driver.AppleIntelKBLGraphics (14.0.3) 1B1F5C29-179F-374D-BACF-919D3A83FBBD <116 115 76 13 8 7 6 5 3 1>
```

**Comment by sirrusyqh** [comment]
Anonymous UUID:       556DAA7D-3966-8ACB-A550-128ED6FB4DD1

Fri Jun 12 22:25:35 2020

*** Panic Report ***
panic(cpu 0 caller 0xffffff8017d88c2d): Kernel trap at 0xffffff7f9a528c88, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000033, CR3: 0x000000001d6c1000, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0xffffff8072537690, RCX: 0x0000000000000202, RDX: 0xffffff838f37b78b
RSP: 0xffffff83b0793a00, RBP: 0xffffff83b0793a30, RSI: 0xffffff83b0793ad0, RDI: 0xffffff8072537690
R8:  0xffffff83b0793870, R9:  0x0000000000000008, R10: 0x0000000000000010, R11: 0x0000000000000000
R12: 0xffffff8072537690, R13: 0xffffff7f9a598700, R14: 0x0000000000000000, R15: 0x0000000000004006
RFL: 0x0000000000010202, RIP: 0xffffff7f9a528c88, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000033, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff83b07934b0 : 0xffffff8017c6e166 
0xffffff83b0793500 : 0xffffff8017d96714 
0xffffff83b0793540 : 0xffffff8017d88a00 
0xffffff83b07935c0 : 0xffffff8017c20180 
0xffffff83b07935e0 : 0xffffff8017c6dbdc 
0xffffff83b0793710 : 0xffffff8017c6d99c 
0xffffff83b0793770 : 0xffffff8017d88c2d 
0xffffff83b07938f0 : 0xffffff8017c20180 
0xffffff83b0793910 : 0xffffff7f9a528c88 
0xffffff83b0793a30 : 0xffffff7f9a540308 
0xffffff83b0793a70 : 0xffffff7f9a540070 
0xffffff83b0793ac0 : 0xffffff7f9a53ffb7 
0xffffff83b0793b20 : 0xffffff7f9a53d765 
0xffffff83b0793b60 : 0xffffff7f9a54298c 
0xffffff83b0793b90 : 0xffffff7f9a547008 
0xffffff83b0793be0 : 0xffffff7f9a5680b4 
0xffffff83b0793c60 : 0xffffff7f9a569459 
0xffffff83b0793ca0 : 0xffffff7f9a56a142 
0xffffff83b0793cf0 : 0xffffff7f9a56160c 
0xffffff83b0793d30 : 0xffffff7f9a565d6d 
0xffffff83b0793d90 : 0xffffff7f9a51e267 
0xffffff83b0793e20 : 0xffffff7f989a5e99 
0xffffff83b0793e70 : 0xffffff7f989a534c 
0xffffff83b0793e90 : 0xffffff7f9a5be0a4 
0xffffff83b0793ed0 : 0xffffff8017ca77e4 
0xffffff83b0793f40 : 0xffffff8017ca7345 
0xffffff83b0793fa0 : 0xffffff8017c1f4f7 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000->0xffffff7f989acfff
         com.apple.driver.AppleACPIPlatform(6.1)[FC118BB9-2E67-35DD-BB25-BA6DFAF5AE88]@0xffffff7f9a518000->0xffffff7f9a5b3fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1850E7DA-E707-3027-A3AA-637C80B57219]@0xffffff7f98494000
            dependency: com.apple.driver.AppleSMC(3.1.9)[497D69E7-C1FB-3435-B4D9-ED1DC51727D1]@0xffffff7f989ad000
         com.apple.driver.AppleACPIEC(6.1)[00F1F962-B55B-3339-80D6-A0787A895E43]@0xffffff7f9a5bd000->0xffffff7f9a5c3fff
            dependency: com.apple.iokit.IOSMBusFamily(1.1)[9CFF73D8-2872-3FC0-AEE5-334587EAA4D0]@0xffffff7f9a473000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000
            dependency: com.apple.driver.AppleACPIPlatform(6.1)[FC118BB9-2E67-35DD-BB25-BA6DFAF5AE88]@0xffffff7f9a518000

BSD process name corresponding to current thread: kernel_task
Boot args: nv_disable=1 dart=0 enable-hdmi20 -v 

Mac OS version:
17E199

Kernel version:
Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Kernel UUID: 1B55340B-0B14-3026-8A47-1E139DB63DA3
Kernel slide:     0x0000000017a00000
Kernel text base: 0xffffff8017c00000
__HIB  text base: 0xffffff8017b00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 2025439706714
last loaded kext at 34951689960: com.realtek.driver.RtWlanU1827	1827.4.b19 (addr 0xffffff7f99228000, size 4100096)
last unloaded kext at 459162044424: org.acidanthera.NVMeFix	1.0.0 (addr 0xffffff7f9b161000, size 20480)
loaded kexts:
(none)

EOF

System Profile:
Thunderbolt Bus: 
Boot Volume File System Type: apfs
PCI Card: Intel HD Graphics 530, VGA compatible controller, Internal@0,2,0
PCI Card: 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller, USB controller, Internal@0,20,0
PCI Card: 100 Series/C230 Series Chipset Family Thermal Subsystem, Signal processing controller, Internal@0,20,2
PCI Card: 100 Series/C230 Series Chipset Family MEI Controller #1, Communication controller, Internal@0,22,0
PCI Card: HM170/QM170 Chipset SATA Controller [AHCI Mode], SATA controller, Internal@0,23,0
PCI Card: 100 Series/C230 Series Chipset Family Power Management Controller, Memory controller, Internal@0,31,2
PCI Card: 100 Series/C230 Series Chipset Family HD Audio Controller, Audio device, Internal@0,31,3
PCI Card: 100 Series/C230 Series Chipset Family SMBus, SMBus, Internal@0,31,4
PCI Card: Intel I219LM2 PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,31,6
PCI Card: RTS522A PCI Express Card Reader, Unassigned class, Internal@0,28,4/0,0
PCI Card: BCM4352 802.11ac Wireless Network Adapter, Network controller, Internal@0,28,0/0,0
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2133 MHz, Samsung, M471A2K43BB1-CPB
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2134 MHz, Crucial Technology, CT16G4SFD8213.C16FAD
USB Device: USB 3.0 Bus
USB Device: Bluetooth HCI
USB Device: USB Receiver
Serial ATA Device: SAMSUNG MZ7LN512HMJP-000L7, 512.11 GB
Serial ATA Device: Lenovo SSD SL700 M.2 256G, 256.06 GB
Model: MacBookPro13,3, BootROM 254.0.0, 4 processors, Intel Core i7, 2.71 GHz, 32 GB, SMC 2.38f7
Graphics: Intel HD Graphics 530, Intel HD Graphics 530, Built-In
Network Service: Ethernet, Ethernet, en0
Bluetooth: Version 6.0.5f3, 3 services, 26 devices, 1 incoming serial ports
Model: MacBookPro13,3, BootROM 254.0.0, 4 processors, Intel Core i7, 2.71 GHz, 32 GB, SMC 2.38f7
Graphics: Intel HD Graphics 530, Intel HD Graphics 530, Built-In
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2133 MHz, Samsung, M471A2K43BB1-CPB
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2134 MHz, Crucial Technology, CT16G4SFD8213.C16FAD
Bluetooth: Version 6.0.5f3, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel HD Graphics 530, VGA compatible controller, Internal@0,2,0
PCI Card: 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller, USB controller, Internal@0,20,0
PCI Card: 100 Series/C230 Series Chipset Family Thermal Subsystem, Signal processing controller, Internal@0,20,2
PCI Card: 100 Series/C230 Series Chipset Family MEI Controller #1, Communication controller, Internal@0,22,0
PCI Card: HM170/QM170 Chipset SATA Controller [AHCI Mode], SATA controller, Internal@0,23,0
PCI Card: 100 Series/C230 Series Chipset Family Power Management Controller, Memory controller, Internal@0,31,2
PCI Card: 100 Series/C230 Series Chipset Family HD Audio Controller, Audio device, Internal@0,31,3
PCI Card: 100 Series/C230 Series Chipset Family SMBus, SMBus, Internal@0,31,4
PCI Card: Intel I219LM2 PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,31,6
PCI Card: RTS522A PCI Express Card Reader, Unassigned class, Internal@0,28,4/0,0
PCI Card: BCM4352 802.11ac Wireless Network Adapter, Network controller, Internal@0,28,0/0,0
Serial ATA Device: SAMSUNG MZ7LN512HMJP-000L7, 512.11 GB
Serial ATA Device: Lenovo SSD SL700 M.2 256G, 256.06 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth HCI
USB Device: USB Receiver
Thunderbolt Bus: 
重启啥原因？
