### ISSUE TITLE
Q370芯片第8代U可否安装？谢谢！

### ISSUE THREAD

**Issue by valorzhang** [W-MS/OptiPlex-7060and7070-Catalina#13]
电脑概览

电脑型号  戴尔 OptiPlex 7070
操作系统  Microsoft Windows 10 企业版 LTSC (64位)
CPU  (英特尔)Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz(3000 MHz)
主板  戴尔 0YNVJG
内存  32.00 GB (   2666 MHz)
主硬盘  1000 GB (希捷 ST1000LM049-2GH172 已使用时间: 146小时)
显卡  NVIDIA GeForce GT 730
显示器  三星 U32H85x 32位真彩色 60Hz
声卡  Realtek Audio
网卡  Intel(R) Ethernet Connection (7) I219-LM

**Comment by W-MS** [comment]
独显不行
