### ISSUE TITLE
请教下，7070m启动读取进度条之后，只有DP线接显示器可以显示，DP转HDMI和DP转DVI都是黑屏

### ISSUE THREAD

**Issue by hahabaobei** [W-MS/OptiPlex-7060and7070-Catalina#14]
正常吗？有办法转HDMI或者DVI显示吗？

我的刚到手，0x8dc要输入0x02才能成功，0x2就提示错误。

之后一切顺利，进入桌面。除了WIFI和蓝牙，一切正常。

只是刚登陆的时候，鼠标有点卡。过段时间就正常了，时间不长。

**Comment by W-MS** [comment]
遇到过同样问题，不能用转换线的。
