### ISSUE TITLE
dell 这个兼容成铭3980电脑吗? 

### ISSUE THREAD

**Issue by zhaifg** [W-MS/OptiPlex-7060and7070-Catalina#20]
dell 这个兼容成铭3980电脑吗? 
也是i5 8500的

**Comment by W-MS** [comment]
不保证使用。只是cpu一样意义不大



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZhaiFG <notifications@github.com&gt;
发送时间: 2020年7月13日 22:56
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] dell 这个兼容成铭3980电脑吗?  (#20)
