### ISSUE TITLE
睡眠和10.15.6

### ISSUE THREAD

**Issue by xuewei8829** [W-MS/OptiPlex-7060and7070-Catalina#21]
先谢谢大神，我已经安装正常使用。目前在使用过程中发现7060MFF 不能自己关闭显示器自动进入睡眠。然后小版本升级到10.15.6 升级失败。不知道您什么时候更新新的EFI呢？

**Comment by W-MS** [comment]
更新一下clover和几个驱动就行，最近在研究opencore了，如有进展会上传



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xuewei8829 <notifications@github.com&gt;
发送时间: 2020年7月17日 22:32
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 睡眠和10.15.6 (#21)





 
先谢谢大神，我已经安装正常使用。目前在使用过程中发现7060MFF 不能自己关闭显示器自动进入睡眠。然后小版本升级到10.15.6 升级失败。不知道您什么时候更新新的EFI呢？

**Comment by laodouya** [comment]
> 更新一下clover和几个驱动就行，最近在研究opencore了，如有进展会上传 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: xuewei8829 <notifications@github.com&gt; 发送时间: 2020年7月17日 22:32 收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 睡眠和10.15.6 (#21) 先谢谢大神，我已经安装正常使用。目前在使用过程中发现7060MFF 不能自己关闭显示器自动进入睡眠。然后小版本升级到10.15.6 升级失败。不知道您什么时候更新新的EFI呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

赞！希望发OC的时候同样集成1820A驱动
