### ISSUE TITLE
setup_var 0x8dc 0x02

### ISSUE THREAD

**Issue by G-Akiraka** [W-MS/OptiPlex-7060and7070-Catalina#23]
原文中写的是  setup_var 0x8dc 0x2
看别人实际写的是 setup_var 0x8dc 0x02 少了一个0

**Comment by W-MS** [comment]
我是说，也许你说的没错，但我实际dump出来的数据如下：
![20200730203637](https://user-images.githubusercontent.com/4151402/88923699-b4eb2400-d2a4-11ea-87b9-9ffbe2bbcdbb.png)
如果你注意看你会发现0x8DC没有0x02.
鉴于Dell的Optiplex系列分为SFF MFF MT等多个型号，我将建议各位自行查阅，而非使用通用代码以防损坏。

**Comment by G-Akiraka** [comment]
后天我的7070也到了，我也不清楚，只是看到别人有这样说。到时候就知道了

**Comment by W-MS** [comment]
通过Dell PFS Extract工具提取一下BIOS(的EXE程序包)，用UEFI Tool找到包含DVMT字段PE32镜像，导出并使用Universal IFR extractor解码自行就能看到地址。

**Comment by G-Akiraka** [comment]
你的是正确的，请问你这个efi升级最新不行？

**Comment by W-MS** [comment]
建议单独dump出来确定



发自我的iPhone


------------------ Original ------------------
