### ISSUE TITLE
使用您的EFI文件出现禁止标志

### ISSUE THREAD

**Issue by lable** [W-MS/OptiPlex-7060and7070-Catalina#3]
硬件环境：
DELL 7060 SFF
i5 8500
16g ddr4 2666

使用如下链接的镜像文件制作U盘并安装系统：
https://blog.daliansky.net/macOS-Catalina-10.15-19A583-Release-version-with-Clover-5093-original-image-Double-EFI-Version.html

将efi文件换成您的，启动出现苹果进度条，读完后出现禁止标志。

# 是没有改 DVMT 引起，还是那个步骤有问题？

DVMT的修改命令如何执行，能提示启动  grub 的efi文件吗？请赐教，感谢！

**Comment by W-MS** [comment]
明天传上来



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lable <notifications@github.com&gt;
发送时间: 2019年11月4日 23:41
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 使用您的EFI文件出现禁止标志 (#3)




硬件环境：
DELL 7060 SFF
i5 8500
16g ddr4 2666

使用如下链接的镜像文件制作U盘并安装系统：
https://blog.daliansky.net/macOS-Catalina-10.15-19A583-Release-version-with-Clover-5093-original-image-Double-EFI-Version.html

将efi文件换成您的，启动出现苹果进度条，读完后出现禁止标志。

是没有改 DVMT 引起，还是那个步骤有问题？

DVMT的修改命令如何执行，能提示启动  grub 的efi文件吗？请赐教，感谢！

**Comment by lable** [comment]
谢谢！

**Comment by lable** [comment]
> 
> 明天传上来 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lable <notifications@github.com&gt; 发送时间: 2019年11月4日 23:41 收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 使用您的EFI文件出现禁止标志 (#3) 硬件环境： DELL 7060 SFF i5 8500 16g ddr4 2666 使用如下链接的镜像文件制作U盘并安装系统： https://blog.daliansky.net/macOS-Catalina-10.15-19A583-Release-version-with-Clover-5093-original-image-Double-EFI-Version.html 将efi文件换成您的，启动出现苹果进度条，读完后出现禁止标志。 是没有改 DVMT 引起，还是那个步骤有问题？ DVMT的修改命令如何执行，能提示启动 grub 的efi文件吗？请赐教，感谢！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有空吗？请指导一下。

**Comment by W-MS** [comment]
已经更新。有问题再评论
