### ISSUE TITLE
7070 Mico 可用这个吗? 

### ISSUE THREAD

**Issue by ningning21** [W-MS/OptiPlex-7060and7070-Catalina#6]
如题

**Comment by W-MS** [comment]
7060和7070全系列主板一致，皆可用。


如解决问题请关闭issue。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ningning21 <notifications@github.com&gt;
发送时间: 2019年12月5日 15:25
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 7070 Mico 可用这个吗?  (#6)




如题
