### ISSUE TITLE
7050可以使用这套EFI吗？或者大佬出一套7050的配置？

### ISSUE THREAD

**Issue by xxmazha** [W-MS/OptiPlex-7060and7070-Catalina#8]
RT。。。

**Comment by W-MS** [comment]
没有机器测试，且问题和此项目无关。。readme.md里面有个友链，可以在那里求助。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mazha <notifications@github.com&gt;
发送时间: 2019年12月16日 15:29
收件人: W-MS/OptiPlex-7060and7070-Catalina <OptiPlex-7060and7070-Catalina@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[W-MS/OptiPlex-7060and7070-Catalina] 7050可以使用这套EFI吗？或者大佬出一套7050的配置？ (#8)
